# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: required

before_install:
- sudp apt-get install -y libmagickcore-dev
- sudp apt-get install -y libmagickwand-dev
