# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: required

before_install:
- sudo apt-get install -y libmagickcore-dev
- sudo apt-get install -y libmagickwand-dev
